CREATE DATABASE TaskManagerDB;

USE TaskManagerDB;

CREATE TABLE Category(
	CategoryID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CategoryName VARCHAR(50) NOT NULL
);
GO

CREATE TABLE Task(
	TaskID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CategoryFK INT NOT NULL,
	TaskName VARCHAR(50) NOT NULL,
	TaskPriority INT NOT NULL,
	TaskDescription VARCHAR(MAX) NOT NULL,
	TaskDate DATETIME2 NOT NULL,

	CONSTRAINT category_fk FOREIGN KEY (CategoryFK) REFERENCES Category(CategoryID)
);
GO